# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

# yamllint disable rule:line-length
---
name: ramenctl

# This workflow will run when developer push a topic branch to their
# fork in github, minimizing noise for maintainers. This
# workflow also runs on nightly basis at 12:00 AM (00:00 UTC)

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual trigger

env:
  # Constants
  GO_VERSION: "1.23.0"
defaults:
  run:
    shell: bash
jobs:
  lint:
    name: Linters
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install prereqs
        run: |
          echo 'APT::Acquire::Retries "5";' | sudo tee /etc/apt/apt.conf.d/80-retries
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip ruby
          sudo gem install mdl
          sudo pip3 install yamllint

      - name: Run linters
        run: ./hack/pre-commit.sh

      - name: Check tidiness
        # Check that modules are tidy, and that generated files were not
        # modified by the pull request. Both validated by empty diff.
        run: |
          make ramenctl
          make examples
          go mod tidy
          git --no-pager diff
          git diff-index --quiet HEAD

  golangci:
    name: Golangci Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          # when the files to be extracted are already present,
          # tar extraction in Golangci Lint fails with the "File exists"
          # errors. These files appear to be present because of
          # cache in setup-go, on disabling the cache we are no more seeing
          # such error. Cache is to be enabled once the fix is available for
          # this issue.
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.0
          working-directory: .
